name: Build

on: [push,pull_request]

jobs:
  Build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dotnet workloads
        run: dotnet workload install android ios tvos

      - name: Build
        run: dotnet pack FreeTypeSharp/FreeTypeSharp.csproj

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} Artifacts
          path: |
            FreeTypeSharp/bin/Release/*.nupkg

  BuildUWP:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: msbuild FreeTypeSharp/FreeTypeSharp.UWP.csproj -t:Restore,Pack /property:Configuration=Release

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }} UWP Artifacts
          path: |
            FreeTypeSharp/bin/Release/*.nupkg